### ISSUE TITLE
what changes to make it work on 2019.3?

### ISSUE THREAD

**Issue by henryw374** [KeshiaRose/JSON-XML-WDC#1]
hi,

Thanks for this project. we have tableau 2019.3 - what changes would I need to make to the source for it to work on that version?

Thanks

**Comment by KeshiaRose** [comment]
Hi @henryw374, the browser used in 2019.3 does not support modern JavaScript (ES6) therefore you would need to downgrade the JavaScript for it to work. (ie: use `var` instead of `let` or `const`, no arrow functions, etc.)
-Keshia

**Comment by henryw374** [comment]
thanks
