### ISSUE TITLE
basic authentication?

### ISSUE THREAD

**Issue by alekseyn1** [KeshiaRose/JSON-XML-WDC#2]
Hi Keshia,
Thank you for this connector.
Any chance you can build in a basic authentication (optional) into it?

Not finding much information on the following (related to the topic):
Will basic authentication credentials be saved for the refreshes? (using Tableau Online)
If not, perhaps a commented-out line where we could save the credentials would be possible?
Thanks in advance for your assistance.

**Comment by KeshiaRose** [comment]
Hi @alekseyn1, I've just updated the WDC with an option for Basic Auth! As for how the password gets stored, it will get saved as long as you have Desktop open. Then if you close Desktop you will need to re-enter it. If you publish to Server/Online there is an option to embed the password. Doing this will securely embed the password for future automated refreshes.

**Comment by alekseyn1** [comment]
Thank you very much for the quick and effective help!

**Comment by alekseyn1** [comment]
Some troubleshooting required. Sent you an email.
