### ISSUE TITLE
RAW POST query?

### ISSUE THREAD

**Issue by quack3d** [KeshiaRose/JSON-XML-WDC#3]
Any chance of adding support for RAW POST query like this one does? https://rdc.codezero.xyz/#/rest-explorer

Your WDC seems much more efficient and it structures the data so nicely before it comes into Tableau. :)

**Comment by KeshiaRose** [comment]
Hmmm, interesting idea! I think we are actually working on a type of REST connector already as a part of WDC 3.0 so I don't think I'll be adding it to this. I'm curious though, what were you using the raw POST for, and what formatting differences did you see?

**Comment by quack3d** [comment]
Ok. Thanks for responding. An API like this one seems to require it: https://api.nsd.no/dbhapiklient/ . Select 'Tabell' number 1 and hit the button 'Spørring - JSON'. The content in the 'Spørring' field is the query.
