### ISSUE TITLE
transpile js in order to support older versions of tableau

### ISSUE THREAD

**Issue by eeddaann** [KeshiaRose/JSON-XML-WDC#4]
Hi @henryw374, the browser used in 2019.3 does not support modern JavaScript (ES6) therefore you would need to downgrade the JavaScript for it to work. (ie: use `var` instead of `let` or `const`, no arrow functions, etc.)
-Keshia

_Originally posted by @KeshiaRose in https://github.com/KeshiaRose/JSON-XML-WDC/issues/1#issuecomment-702788519_

According to your answer I believe it could be solved by using tools like Babel to transpile the js code. Do you know which version/browser those versions of tableau use? so I'll be able to configure Babel correctly and create a pull request.

**Comment by KeshiaRose** [comment]
Sorry for the late reply! I believe it was Qt WebKit 5.4
